[theme]
base = "light"
primaryColor = "#10B981"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0FDF4"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
